### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by carlmagi** [christiancheng15/StockX-360#1]
Hi bro,

I really hoped this would work! It's not working locally. Do you use anything to bypass some kind of bot protection? I keep getting error 403 when running it.

**Comment by christiancheng15** [comment]
Hi, sadly I think StockX seems to have changed their API access

**Comment by christiancheng15** [comment]
Hi, sadly I think StockX seems to have changed their API access

**Comment by carlmagi** [comment]
Damn. So no way of doing this differently then?
